### ISSUE TITLE
I18n issues in version 3.0.5

### ISSUE THREAD

**Issue by almaron** [mislav/will_paginate#378]
Here is my will_paginate.ru.yml from config/locales: 

```
ru:
  will_paginate:
     previous_label: "&#8592; Назад"
     next_label: "Вперед &#8594;"
     page_gap: "&hellip;"
```

When I try to use the helper in my blog app like this 

```
= will_paginate @posts
```

or this

```
= will_paginate @posts, :previous_label => t("will_paginate.previous_label"), :next_label => t("will_paginate.next_label")
```

it still gives the default labels.
