### ISSUE TITLE
i18n translations doesnt work in 3.1.0

### ISSUE THREAD

**Issue by ndesorden** [mislav/will_paginate#466]
With 3.0.7 everything works fine, but with 3.1.0 translations in yml file are ignored

**Comment by mislav** [comment]
Thanks for reporting! That's weird, since 3.1.0 didn't change anything regarding how translations are looked up. Which Rails version is this with? What are some sample translations that don't get loaded and where are they stored?

**Comment by ndesorden** [comment]
Hi, thanks to you for your great work!
Rails 4.2.5 and ruby 2.2.3, with translations config/locales/es.yml and en.yml. (windows 8 and mac osx) with all translations:

    will_paginate:
      previous_label: "&#8592; Anterior"
      next_label: "Siguiente &#8594;"
      page_gap: "&hellip;"
      page_entries_info:
        single_page:

But SORRY, now i've upgraded to 3.1.0 again and translations are OK!!!!.
I'm confused. I'm using with will-paginate-bootstrap, but i swear not getting texts in Spanish
Sorry again

**Comment by gPrado** [comment]
I ran into a similar problem, but it's still unsolved. Previously I was using version 3.0.7 and everything worked perfectly.
My custom translations for _pt-BR_ locale are correctly loaded, however my translations for _en_ are ignored, only the default ones are displayed.
More specifically, these are the translations that are not being updated:

```yml
en:
  will_paginate:
    page_entries_info:
      multi_page: "Displaying %{from} - %{to} of %{count}"
      multi_page_html: "Displaying <b>%{from}&nbsp;-&nbsp;%{to}</b> of <b>%{count}</b>"
```

Also, I'm using Rails 3.2.22.

Do you have any ideas on what's happening?

Thanks!
