### ISSUE TITLE
Upgrading to 3.1.0 from 3.0.7 overrides the i18n translations in our app

### ISSUE THREAD

**Issue by soma** [mislav/will_paginate#475]
Hello!

We just upgraded from 3.0.7 to the latest version 3.1.0, and our application has yml files that specifies how the pagination should be translated. Previous version worked as desired, our translations were used. But in this last update the "default" translations was used instead of our ones.

**Comment by henrik** [comment]
Same team as @soma. Some more details:

We have YML files like

``` yml
en:
  will_paginate:
    next_label: ►
    page_gap: "&hellip;"
    previous_label: ◄
```

After this upgrade, pages in our default locale (English) stopped showing our custom "◄" etc and instead showed the built-in defaults, "<- Previous page" or something like that. But pages in another locale (Swedish) did show our custom text.
